package com.owo233.tcqt

import android.app.Application
import android.os.SystemClock
import com.owo233.tcqt.activity.FeatureOptionGroup
import com.owo233.tcqt.activity.FeatureSliderField
import com.owo233.tcqt.activity.OptionItem
import com.owo233.tcqt.activity.SettingFeature
import com.owo233.tcqt.activity.TextAreaField
import com.owo233.tcqt.data.TCQTBuild
import com.owo233.tcqt.ext.ActionProcess
import com.owo233.tcqt.ext.ActionPriority
import com.owo233.tcqt.ext.ActionUiType
import com.owo233.tcqt.ext.BooleanSetting
import com.owo233.tcqt.ext.IAction
import com.owo233.tcqt.ext.IntSetting
import com.owo233.tcqt.ext.IntSliderSetting
import com.owo233.tcqt.ext.MultiIntSetting
import com.owo233.tcqt.ext.StringSetting
import com.owo233.tcqt.generated.GeneratedActionList
import com.owo233.tcqt.internals.setting.TCQTSetting
import com.owo233.tcqt.utils.dexkit.DexKitCache
import com.owo233.tcqt.utils.dexkit.DexKitTask
import com.owo233.tcqt.utils.log.Log
import com.owo233.tcqt.utils.log.LogAndroid
import com.owo233.tcqt.utils.reflect.getObject
import com.owo233.tcqt.utils.reflect.new
import java.util.EnumMap
import java.util.concurrent.ConcurrentHashMap
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.coroutines.yield

/**
 * 一次启动中要执行的功能计划。
 *
 * [ActionManager.buildPlan] 只负责“决定执行什么”（进程过滤 + DexKit 缺失过滤 +
 * 按 [ActionPriority] 分组），不负责“什么时候执行”：
 * - [critical] 由调用方在 Application.onCreate 的 Before 回调中同步执行；
 * - 其余由 [StartupScheduler] 在 onCreate 返回后分批在后台线程执行。
 */
data class ActionPlan(
    val critical: List<Class<out IAction>> = emptyList(),
    val early: List<Class<out IAction>> = emptyList(),
    val deferred: List<Class<out IAction>> = emptyList(),
    val background: List<Class<out IAction>> = emptyList(),
) {
    val isEmpty: Boolean
        get() = critical.isEmpty() && early.isEmpty() && deferred.isEmpty() && background.isEmpty()
}

internal object ActionManager {

    /** 后台分批安装时每批的 Action 数量，防止一次性吃满 CPU。 */
    private const val BATCH_SIZE = 8

    private val FIRST_ACTION = GeneratedActionList.ACTIONS // generated by KSP

    private val instanceMap = ConcurrentHashMap<Class<out IAction>, IAction>()

    private val failedActions = ConcurrentHashMap.newKeySet<Class<out IAction>>()

    /**
     * key -> ActionClass。仅设置 UI 需要，延迟到首次访问才构建，
     * 避免启动路径为构建它而实例化全部 Action。
     */
    private val keyToActionMap: Map<String, Class<out IAction>> by lazy {
        val map = hashMapOf<String, Class<out IAction>>()
        FIRST_ACTION.forEach { actionClass ->
            runCatching {
                val action = instanceOf(actionClass) ?: return@forEach
                if (action.key.isNotBlank()) {
                    map[action.key] = actionClass
                }
                action.settings.forEach { setting ->
                    map[setting.key] = actionClass
                }
            }
        }
        map
    }

    private fun instanceOf(cls: Class<out IAction>): IAction? {
        if (cls in failedActions) return null

        return runCatching {
            instanceMap.getOrPut(cls) {
                try {
                    cls.getObject("INSTANCE") as IAction
                } catch (_: NoSuchFieldException) {
                    cls.new()
                }
            }
        }.getOrElse { e ->
            Log.e("ActionManager instanceOf failed", e)
            failedActions.add(cls)
            null
        }
    }

    // ── 启动路径 ────────────────────────────────────────────────────────────

    private val BASE_PROCS = setOf(
        ActionProcess.MSF,
        ActionProcess.MAIN,
        ActionProcess.TOOL,
        ActionProcess.OPENSDK,
        ActionProcess.QZONE,
        ActionProcess.QQFAV
    )

    /**
     * 决定本进程要执行哪些功能，并按优先级分组。不执行任何 Action；
     * 执行由 [runCritical] / [runEarly] / [runDeferred] / [runBackground] 负责。
     */
    fun buildPlan(
        proc: ActionProcess,
        missingDexKitKeys: Set<String>? = null
    ): ActionPlan {
        val lists = EnumMap<ActionPriority, MutableList<Class<out IAction>>>(
            ActionPriority::class.java
        )
        ActionPriority.entries.forEach { lists[it] = mutableListOf() }

        FIRST_ACTION.forEach { actionClass ->
            // DexKit 依赖检查：缺失 key 的 DexKitTask 本轮跳过（等后台查找 + 重启后再装）
            if (DexKitTask::class.java.isAssignableFrom(actionClass)) {
                val dexKitTask = runCatching {
                    instanceOf(actionClass) as? DexKitTask
                }.getOrNull()
                if (dexKitTask != null) {
                    val taskKeys = dexKitTask.getCacheKeys()
                    val shouldSkip = taskKeys.any { key ->
                        (missingDexKitKeys != null && key in missingDexKitKeys) ||
                                DexKitCache.cacheMap[key]?.isEmpty() == true
                    }
                    if (shouldSkip) {
                        return@forEach
                    }
                }
            }

            val action = instanceOf(actionClass) ?: run {
                if (TCQTBuild.DEBUG) {
                    Log.e("instanceOf [${actionClass.simpleName}] failed")
                }
                return@forEach
            }

            val shouldRun =
                ActionProcess.ALL in action.processes ||
                        proc in action.processes ||
                        (ActionProcess.OTHER in action.processes && proc !in BASE_PROCS)
            if (!shouldRun) return@forEach

            lists.getValue(action.priority).add(actionClass)
        }

        return ActionPlan(
            critical = lists[ActionPriority.CRITICAL] ?: emptyList(),
            early = lists[ActionPriority.EARLY] ?: emptyList(),
            deferred = lists[ActionPriority.DEFERRED] ?: emptyList(),
            background = lists[ActionPriority.BACKGROUND] ?: emptyList(),
        )
    }

    /** 同步执行 [ActionPlan.critical]，必须保持在主线程且数量尽量少。 */
    fun runCritical(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runAll(app, proc, plan.critical, "Critical")
    }

    /** onCreate 返回后立刻在后台线程执行 [ActionPlan.early]。 */
    fun runEarly(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runAll(app, proc, plan.early, "Early")
    }

    /** 后台分批执行 [ActionPlan.deferred]。 */
    suspend fun runDeferred(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runBatched(app, proc, plan.deferred, "Deferred")
    }

    /** 后台分批执行 [ActionPlan.background]。 */
    suspend fun runBackground(app: Application, proc: ActionProcess, plan: ActionPlan) {
        runBatched(app, proc, plan.background, "Background")
    }

    private fun runAll(
        app: Application,
        proc: ActionProcess,
        classes: List<Class<out IAction>>,
        tag: String
    ) {
        if (classes.isEmpty()) return
        val phaseStart = SystemClock.elapsedRealtime()
        classes.forEach { executeOne(it, app, proc) }
        val phaseCost = SystemClock.elapsedRealtime() - phaseStart
        LogAndroid.d("[ActionPerf] [$tag] ${classes.size} 个功能共耗时 ${phaseCost}ms")
    }

    private suspend fun runBatched(
        app: Application,
        proc: ActionProcess,
        classes: List<Class<out IAction>>,
        tag: String
    ) {
        if (classes.isEmpty()) return
        val phaseStart = SystemClock.elapsedRealtime()
        val batches = classes.chunked(BATCH_SIZE)
        batches.forEachIndexed { index, batch ->
            withContext(Dispatchers.Default) {
                batch.forEach { executeOne(it, app, proc) }
            }
            // 让出调度，避免一次性吃满后台 CPU / 与宿主后台任务争抢
            if (index != batches.lastIndex) {
                yield()
            }
        }
        val phaseCost = SystemClock.elapsedRealtime() - phaseStart
        LogAndroid.d("[ActionPerf] [$tag] ${classes.size} 个功能共耗时 ${phaseCost}ms")
    }

    private fun executeOne(
        actionClass: Class<out IAction>,
        app: Application,
        proc: ActionProcess
    ) {
        val start = SystemClock.elapsedRealtime()
        runCatching {
            val action = instanceOf(actionClass) ?: return
            action(app, proc)
        }.onFailure { e ->
            Log.e("Action [${actionClass.simpleName}] 执行异常", e)
        }
        val cost = SystemClock.elapsedRealtime() - start
        if (TCQTBuild.DEBUG || cost >= 30) {
            LogAndroid.d(
                "[ActionPerf] ${actionClass.simpleName}: ${cost}ms [${Thread.currentThread().name}]"
            )
        }
    }

    // ── UI 路径（设置界面） ─────────────────────────────────────────────────

    fun resolve(action: IAction): String {
        if (action.name.isNotBlank()) {
            return action.name
        }
        if (action.key.isNotBlank()) {
            return action.key
        }
        return action::class.simpleName ?: "Unknown"
    }

    fun getActionByKey(key: String): IAction? {
        val actionClass = keyToActionMap[key] ?: return null
        return instanceOf(actionClass)
    }

    private val initReadyCache = ConcurrentHashMap<String, Boolean>()

    /**
     * 查询功能是否满足执行条件（[IAction.onInit] 是否返回 true）。
     *
     * 仅供设置界面判断强制禁用状态使用。onInit 应保持为纯条件判断，
     * 有副作用的初始化逻辑请放在 [IAction.onRun] 中。
     */
    fun isInitReady(key: String): Boolean {
        val action = getActionByKey(key) ?: return true
        return initReadyCache.getOrPut(key) {
            runCatching { action.onInit() }.getOrDefault(true)
        }
    }

    fun getSettingDesc(key: String, defaultDesc: String): String {
        val action = getActionByKey(key) ?: return defaultDesc
        return action.getSettingDesc(key) ?: defaultDesc
    }

    fun registerAllSettings(map: HashMap<String, TCQTSetting.Setting<out Any>>) {
        FIRST_ACTION.forEach { actionClass ->
            val action = instanceOf(actionClass) ?: return@forEach
            if (action.key.isNotBlank() && action.uiType == ActionUiType.SWITCH) {
                map[action.key] = TCQTSetting.Setting(
                    action.key,
                    TCQTSetting.SettingType.BOOLEAN,
                    action.defaultEnabled
                )
            }
            action.settings.forEach { s ->
                val type = when (s) {
                    is BooleanSetting -> TCQTSetting.SettingType.BOOLEAN
                    is StringSetting -> TCQTSetting.SettingType.STRING
                    is IntSetting -> TCQTSetting.SettingType.INT
                    is IntSliderSetting -> TCQTSetting.SettingType.INT
                    is MultiIntSetting -> TCQTSetting.SettingType.INT_MULTI
                }
                map[s.key] = TCQTSetting.Setting(
                    s.key,
                    type,
                    s.defaultValue
                )
            }
        }
    }

    fun getAllFeatures(): List<SettingFeature> {
        val features = mutableListOf<SettingFeature>()
        FIRST_ACTION.forEach { actionClass ->
            val action = instanceOf(actionClass) ?: return@forEach
            if (action.key.isBlank() || action.hidden) return@forEach

            val textAreas = action.settings
                .filterIsInstance<StringSetting>()
                .filterNot { it.isHide }
                .map { s ->
                    TextAreaField(
                        key = s.key,
                        label = s.name,
                        placeholder = s.placeholder.ifEmpty { "填写${s.name}内容" }
                    )
                }

            val optionGroups = action.settings
                .filter { (it is IntSetting || it is MultiIntSetting) && !it.isHide }
                .map { s ->
                    val options = when (s) {
                        is IntSetting -> s.options
                        is MultiIntSetting -> s.options
                        else -> emptyList()
                    }
                    FeatureOptionGroup(
                        key = s.key,
                        title = s.name,
                        isMulti = s is MultiIntSetting,
                        fallbackValue = s.defaultValue as Int,
                        options = options.mapIndexed { i, label ->
                            OptionItem(label = label, value = i + 1)
                        },
                        forcedSelections = (s as? MultiIntSetting)?.forcedSelections.orEmpty()
                    )
                }

            val sliders = action.settings
                .filterIsInstance<IntSliderSetting>()
                .filterNot { it.isHide }
                .map { s ->
                    FeatureSliderField(
                        key = s.key,
                        label = s.name,
                        min = s.min,
                        max = s.max,
                        step = s.step,
                        suffix = s.suffix,
                        defaultValue = s.defaultValue
                    )
                }

            val categoryPath =
                action.uiTab.trim().split("/").map { it.trim() }.filter { it.isNotEmpty() }
                    .ifEmpty { listOf("基础") }

            features.add(
                SettingFeature(
                    key = action.key,
                    label = action.name,
                    staticDesc = action.desc,
                    order = action.uiOrder,
                    tab = action.uiTab.ifBlank { "基础" },
                    categoryPath = categoryPath,
                    uiType = action.uiType,
                    textAreas = textAreas,
                    optionGroups = optionGroups,
                    sliders = sliders
                )
            )
        }
        return features
    }
}
